services:
  - type: web
    name: personalwebsite
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 3 personalwebsite.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: personalwebsite.onrender.com
      - key: DB_ENGINE
        value: django.db.backends.postgresql
      - key: DB_NAME
        fromDatabase:
          name: personalwebsite-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: personalwebsite-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: personalwebsite-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: personalwebsite-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: personalwebsite-db
          property: port

databases:
  - name: personalwebsite-db
    databaseName: personalwebsite
    user: personalwebsite

