services:
  - type: web
    name: personalwebsite
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && python manage.py createsuperuser --noinput || true && gunicorn --bind 0.0.0.0:$PORT --workers 3 personalwebsite.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@example.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "admin"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: personalwebsite-0xwa.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: personalwebsite-db
          property: connectionString

databases:
  - name: personalwebsite-db
    databaseName: personalwebsite
    user: personalwebsite
    plan: free

